wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: huggingface
    huggingface_version: 4.12.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.3
    start_time: 1659792869.039362
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 51
      - 53
      - 55
      3:
      - 1
      - 23
      4: 3.8.3
      5: 0.13.1
      6: 4.12.5
      8:
      - 3
      - 5
